const iconMapper = {
  market: require("@/assets/images/market.svg"),
  food: require("@/assets/images/Food.svg"),
  salary: require("@/assets/images/Salary.svg"),
  rent: require("@/assets/images/rent.svg"),
  transport: require("@/assets/images/transport.svg"),
  more: require("@/assets/images/more.svg"),
  medicine: require("@/assets/images/medicine.svg"),
  entertainment: require("@/assets/images/entertainment.svg"),
  saving: require("@/assets/images/saving.svg"),
  gift: require("@/assets/images/gift.svg"),
  travel: require("@/assets/images/travel.svg"),
  wedding: require("@/assets/images/wedding.svg"),
  newHome: require("@/assets/images/newHome.svg"),
  car: require("@/assets/images/Car.svg"),
  profile: require("@/assets/images/profile.svg"),
  setting: require("@/assets/images/setting.svg"),
  security: require("@/assets/images/security.svg"),
  help: require("@/assets/images/help.svg"),
  logout: require("@/assets/images/logout.svg"),
  helpDark: require("@/assets/images/helpDark.svg"),
  whatapp: require("@/assets/images/whatapp.svg"),
  instagram: require("@/assets/images/instagram.svg"),
  website: require("@/assets/images/website.svg"),
  facebook: require("@/assets/images/Facebook.svg"),
};
export default iconMapper;
